### ISSUE TITLE
Downloading 110kb files

### ISSUE THREAD

**Issue by imahmud1** [fahidsarker/h5ai_downloader#1]
Sometimes on a running process, it starts downloading files which are 110.95k to be precise. It creates the related folder and downloads the exact file type but the size is 110.95k
Is there any way I can redownload those specific URLs?

**Comment by fahidsarker** [comment]
Can you provide more details? If the files are 110.95k and the downloaded files are 110.95k, what is the issue (or am I missing something 😃)? You can redownload the URLs by deleting the downloaded folder.

**Comment by fahidsarker** [comment]
Closed due to no response
